name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    permissions: write-all
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_KEY }}

